# конфигурационные данные
# go get github.com/spf13/viper


port: "9000"
db:
  port: "5436"
  user: "postgres"
  name: "postgres"
  # password: "" лежит в .env
  host: "localhost"
  sslmode: "disable"